import { FoodDatabaseItem } from './types';

export const CONDIMENTS_EXTRAS_DATABASE: FoodDatabaseItem[] = [
  {
    id: 'proteina-whey',
    name: 'Proteína Whey Isolate / Concentrado en Polvo',
    aliases: ['proteina en polvo', 'whey', 'proteina whey', 'batido de proteinas', 'isolate'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 30,
    icon: '🥛',
    per100g: { calories: 375, protein: 85.0, carbs: 3.0, fats: 2.0 },
    thyroidFriendly: true,
  },
  {
    id: 'cacao-puro-desgrasado',
    name: 'Cacao Puro 100% Desgrasado en Polvo',
    aliases: ['cacao puro', 'cacao 100', 'cacao en polvo'],
    category: 'especias_otros',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🍫',
    per100g: { calories: 310, protein: 25.0, carbs: 14.0, fats: 11.0 },
    perTablespoon: { calories: 31, protein: 2.5, carbs: 1.4, fats: 1.1 },
    thyroidFriendly: true,
    thyroidNote: 'Flavanoles de cacao y magnesio neuroprotector.',
  },
  {
    id: 'chocolate-negro-85-90',
    name: 'Chocolate Negro 85% - 90%',
    aliases: ['chocolate negro', 'chocolate 85', 'chocolate 90', 'onza de chocolate'],
    category: 'especias_otros',
    defaultUnit: 'g',
    defaultAmount: 20,
    icon: '🍫',
    per100g: { calories: 590, protein: 11.0, carbs: 20.0, fats: 49.0 },
    thyroidFriendly: true,
  },
  {
    id: 'canela-ceilan',
    name: 'Canela de Ceilán en Polvo',
    aliases: ['canela', 'canela en polvo', 'canela de ceilan'],
    category: 'especias_otros',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🪵',
    per100g: { calories: 247, protein: 4.0, carbs: 80.0, fats: 1.2 },
    perTablespoon: { calories: 12, protein: 0.2, carbs: 4.0, fats: 0.05 },
    thyroidFriendly: true,
    thyroidNote: 'Mejora la sensibilidad a la insulina celular.',
  },
  {
    id: 'curcuma-pimienta',
    name: 'Cúrcuma en Polvo (con Pimienta Negra)',
    aliases: ['curcuma', 'cúrcuma'],
    category: 'especias_otros',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🟡',
    per100g: { calories: 312, protein: 9.7, carbs: 67.0, fats: 3.2 },
    perTablespoon: { calories: 15, protein: 0.5, carbs: 3.3, fats: 0.15 },
    thyroidFriendly: true,
    thyroidNote: 'Curcumina moduladora de la inflamación tiroidea.',
  },
  {
    id: 'sal-yodada',
    name: 'Sal Marina Yodada',
    aliases: ['sal', 'sal yodada', 'sal marina'],
    category: 'especias_otros',
    defaultUnit: 'g',
    defaultAmount: 2,
    icon: '🧂',
    per100g: { calories: 0, protein: 0, carbs: 0, fats: 0 },
    thyroidFriendly: true,
    thyroidNote: 'Asegura los 150 mcg diarios de yodo necesarios para sintetizar hormonas tiroideas.',
  },
  {
    id: 'miel-pura-abeja',
    name: 'Miel Pura de Abeja',
    aliases: ['miel', 'miel de abeja'],
    category: 'especias_otros',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🍯',
    per100g: { calories: 304, protein: 0.3, carbs: 82.4, fats: 0 },
    perTablespoon: { calories: 45, protein: 0.05, carbs: 12.3, fats: 0 },
    thyroidFriendly: true,
  },
  {
    id: 'sirope-arce-agave',
    name: 'Sirope de Arce / Agave',
    aliases: ['sirope de arce', 'sirope de agave', 'arce'],
    category: 'especias_otros',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🍁',
    per100g: { calories: 260, protein: 0, carbs: 67.0, fats: 0 },
    perTablespoon: { calories: 39, protein: 0, carbs: 10.0, fats: 0 },
    thyroidFriendly: true,
  },
  {
    id: 'salsa-soja-tamari',
    name: 'Salsa de Soja Baja en Sal / Tamari Sin Gluten',
    aliases: ['salsa de soja', 'tamari', 'soja salsa'],
    category: 'especias_otros',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🥢',
    per100g: { calories: 53, protein: 5.5, carbs: 6.0, fats: 0.1 },
    perTablespoon: { calories: 8, protein: 0.8, carbs: 0.9, fats: 0.01 },
    thyroidFriendly: true,
  },
  {
    id: 'mostaza-dijon',
    name: 'Mostaza de Dijon / Clásica',
    aliases: ['mostaza', 'mostaza dijon', 'mostaza antigua'],
    category: 'especias_otros',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🟡',
    per100g: { calories: 66, protein: 4.4, carbs: 5.0, fats: 4.0 },
    perTablespoon: { calories: 10, protein: 0.6, carbs: 0.7, fats: 0.6 },
    thyroidFriendly: true,
  },
  {
    id: 'mayonesa',
    name: 'Mayonesa Casera / Aceite de Oliva',
    aliases: ['mayonesa', 'mahonesa'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🥣',
    per100g: { calories: 680, protein: 1.0, carbs: 1.0, fats: 75.0 },
    perTablespoon: { calories: 100, protein: 0.15, carbs: 0.15, fats: 11.0 },
    thyroidFriendly: true,
  },
  {
    id: 'caldo-huesos-pollo-verduras',
    name: 'Caldo de Huesos / Pollo / Verduras Casero',
    aliases: ['caldo de huesos', 'caldo de pollo', 'caldo de verduras', 'consome'],
    category: 'carnes_pescados',
    defaultUnit: 'ml',
    defaultAmount: 250,
    icon: '🍲',
    per100g: { calories: 18, protein: 3.5, carbs: 0.5, fats: 0.3 },
    thyroidFriendly: true,
    thyroidNote: 'Colágeno, glutamina y glicina para reparar la mucosa gastrointestinal.',
  }
];
