import { FoodDatabaseItem } from './types';

export const DAIRY_EGGS_DATABASE: FoodDatabaseItem[] = [
  {
    id: 'huevo-l',
    name: 'Huevo Entero (Talla L)',
    aliases: ['huevo', 'huevos', 'huevo cocido', 'huevo frito', 'huevo duro', 'huevo a la plancha', 'tortilla francesa'],
    category: 'lacteos_huevos',
    defaultUnit: 'ud',
    defaultAmount: 2,
    icon: '🥚',
    per100g: { calories: 143, protein: 12.6, carbs: 0.7, fats: 9.5 },
    perUnit: { calories: 80, protein: 7.0, carbs: 0.4, fats: 5.3 },
    thyroidFriendly: true,
    thyroidNote: 'La yema contiene colina, vitamina D3, selenio, yodo y todos los aminoácidos esenciales.',
  },
  {
    id: 'claras-huevo',
    name: 'Claras de Huevo (Pasteurizadas)',
    aliases: ['claras', 'claras de huevo', 'clara de huevo', 'tortilla de claras'],
    category: 'lacteos_huevos',
    defaultUnit: 'ml',
    defaultAmount: 200,
    icon: '🥚',
    per100g: { calories: 52, protein: 11.0, carbs: 0.7, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'huevo-codorniz',
    name: 'Huevos de Codorniz',
    aliases: ['huevo de codorniz', 'huevos de codorniz'],
    category: 'lacteos_huevos',
    defaultUnit: 'ud',
    defaultAmount: 4,
    icon: '🥚',
    per100g: { calories: 158, protein: 13.0, carbs: 0.4, fats: 11.0 },
    perUnit: { calories: 16, protein: 1.3, carbs: 0.05, fats: 1.1 },
    thyroidFriendly: true,
  },
  {
    id: 'yogur-griego-natural',
    name: 'Yogur Griego Natural (Sin Azúcar)',
    aliases: ['yogur griego', 'griego natural', 'yogurt griego'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥛',
    per100g: { calories: 115, protein: 9.0, carbs: 4.0, fats: 7.0 },
    thyroidFriendly: true,
    thyroidNote: 'Excelente probiótico para la microbiota intestinal.',
  },
  {
    id: 'yogur-natural',
    name: 'Yogur Natural Clásico',
    aliases: ['yogur', 'yogur natural', 'yogurt'],
    category: 'lacteos_huevos',
    defaultUnit: 'ud',
    defaultAmount: 1,
    icon: '🥛',
    per100g: { calories: 61, protein: 3.5, carbs: 4.7, fats: 3.3 },
    perUnit: { calories: 76, protein: 4.4, carbs: 5.9, fats: 4.1 },
    thyroidFriendly: true,
  },
  {
    id: 'skyr',
    name: 'Skyr Natural (0% Grasa)',
    aliases: ['skyr', 'skyr natural', 'yogur skyr'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥛',
    per100g: { calories: 65, protein: 11.5, carbs: 4.0, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'kefir',
    name: 'Kéfir Natural',
    aliases: ['kefir', 'kéfir', 'kefir de leche'],
    category: 'lacteos_huevos',
    defaultUnit: 'ml',
    defaultAmount: 200,
    icon: '🥛',
    per100g: { calories: 60, protein: 3.8, carbs: 4.5, fats: 3.0 },
    thyroidFriendly: true,
  },
  {
    id: 'queso-fresco-batido',
    name: 'Queso Fresco Batido 0% / Quark',
    aliases: ['queso batido', 'queso fresco batido', 'quark', 'queso 0%'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🥣',
    per100g: { calories: 48, protein: 8.5, carbs: 3.5, fats: 0.1 },
    thyroidFriendly: true,
  },
  {
    id: 'queso-cottage-requeson',
    name: 'Queso Cottage / Requesón',
    aliases: ['cottage', 'requeson', 'queso cottage', 'requesón', 'ricotta'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🧀',
    per100g: { calories: 98, protein: 11.5, carbs: 3.4, fats: 4.3 },
    thyroidFriendly: true,
  },
  {
    id: 'queso-burgos',
    name: 'Queso Fresco Tipo Burgos',
    aliases: ['queso fresco', 'queso burgos', 'queso de burgos'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🧀',
    per100g: { calories: 175, protein: 11.0, carbs: 3.0, fats: 13.0 },
    thyroidFriendly: true,
  },
  {
    id: 'mozzarella-fresca',
    name: 'Mozzarella Fresca',
    aliases: ['mozzarella', 'queso mozzarella', 'burrata'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🧀',
    per100g: { calories: 280, protein: 18.0, carbs: 1.5, fats: 22.0 },
    thyroidFriendly: true,
  },
  {
    id: 'queso-semicurado-manchego',
    name: 'Queso Semicurado Manchego / Oveja',
    aliases: ['queso semicurado', 'queso curado', 'queso manchego', 'queso de oveja', 'queso de cabra'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 40,
    icon: '🧀',
    per100g: { calories: 390, protein: 25.0, carbs: 1.0, fats: 32.0 },
    thyroidFriendly: true,
  },
  {
    id: 'queso-parmesano',
    name: 'Queso Parmesano / Grana Padano',
    aliases: ['parmesano', 'queso parmesano', 'grana padano', 'parmigiano'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 25,
    icon: '🧀',
    per100g: { calories: 431, protein: 38.0, carbs: 4.1, fats: 29.0 },
    thyroidFriendly: true,
  },
  {
    id: 'queso-feta',
    name: 'Queso Feta Griego',
    aliases: ['queso feta', 'feta'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 50,
    icon: '🧀',
    per100g: { calories: 264, protein: 14.2, carbs: 4.1, fats: 21.3 },
    thyroidFriendly: true,
  },
  {
    id: 'queso-gouda-cheddar-havarti',
    name: 'Queso Cheddar / Gouda / Havarti / Emmental',
    aliases: ['cheddar', 'gouda', 'havarti', 'emmental', 'queso lonchas'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 40,
    icon: '🧀',
    per100g: { calories: 380, protein: 24.0, carbs: 1.5, fats: 30.0 },
    thyroidFriendly: true,
  },
  {
    id: 'queso-azul-roquefort',
    name: 'Queso Azul / Roquefort / Cabrales / Gorgonzola',
    aliases: ['queso azul', 'roquefort', 'cabrales', 'gorgonzola'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 30,
    icon: '🧀',
    per100g: { calories: 353, protein: 21.4, carbs: 2.3, fats: 28.7 },
    thyroidFriendly: true,
  },
  {
    id: 'leche-vaca',
    name: 'Leche de Vaca (Entera / Semidesnatada / Desnatada)',
    aliases: ['leche', 'leche semidesnatada', 'leche entera', 'leche desnatada', 'vaso de leche'],
    category: 'lacteos_huevos',
    defaultUnit: 'ml',
    defaultAmount: 200,
    icon: '🥛',
    per100g: { calories: 46, protein: 3.2, carbs: 4.8, fats: 1.6 },
    thyroidFriendly: true,
  },
  {
    id: 'nata-cocinar',
    name: 'Nata Ligera para Cocinar (15% MG)',
    aliases: ['nata', 'nata para cocinar', 'crema de leche'],
    category: 'lacteos_huevos',
    defaultUnit: 'ml',
    defaultAmount: 50,
    icon: '🥛',
    per100g: { calories: 160, protein: 2.8, carbs: 4.0, fats: 15.0 },
    thyroidFriendly: true,
  },
  {
    id: 'bebida-soja',
    name: 'Bebida de Soja (Sin Azúcar Añadido)',
    aliases: ['leche de soja', 'bebida de soja'],
    category: 'lacteos_huevos',
    defaultUnit: 'ml',
    defaultAmount: 200,
    icon: '🥛',
    per100g: { calories: 33, protein: 3.3, carbs: 1.2, fats: 1.8 },
    thyroidFriendly: true,
    thyroidNote: 'En hipotiroidismo separar 2-3h de la toma de levotiroxina.',
  },
  {
    id: 'bebida-almendra',
    name: 'Bebida de Almendras (Zero Azúcares)',
    aliases: ['leche de almendras', 'bebida de almendras'],
    category: 'lacteos_huevos',
    defaultUnit: 'ml',
    defaultAmount: 200,
    icon: '🥛',
    per100g: { calories: 14, protein: 0.5, carbs: 0.2, fats: 1.2 },
    thyroidFriendly: true,
  },
  {
    id: 'bebida-avena',
    name: 'Bebida de Avena',
    aliases: ['leche de avena', 'bebida de avena'],
    category: 'lacteos_huevos',
    defaultUnit: 'ml',
    defaultAmount: 200,
    icon: '🥛',
    per100g: { calories: 45, protein: 1.0, carbs: 7.5, fats: 1.2 },
    thyroidFriendly: true,
  },
  {
    id: 'bebida-arroz-coco',
    name: 'Bebida de Arroz / Coco',
    aliases: ['leche de coco', 'bebida de arroz', 'leche de arroz'],
    category: 'lacteos_huevos',
    defaultUnit: 'ml',
    defaultAmount: 200,
    icon: '🥥',
    per100g: { calories: 48, protein: 0.2, carbs: 9.8, fats: 1.0 },
    thyroidFriendly: true,
  },
  {
    id: 'tofu-firme',
    name: 'Tofu Firme Natural',
    aliases: ['tofu', 'tofu firme', 'tofu a la plancha'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🧈',
    per100g: { calories: 125, protein: 13.5, carbs: 1.8, fats: 7.0 },
    thyroidFriendly: true,
    thyroidNote: 'Proteína vegetal completa. Consumir cocinado.',
  },
  {
    id: 'tempeh',
    name: 'Tempeh Fermentado (Soja)',
    aliases: ['tempeh', 'tempe'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 120,
    icon: '🍱',
    per100g: { calories: 192, protein: 19.0, carbs: 9.0, fats: 11.0 },
    thyroidFriendly: true,
  },
  {
    id: 'seitan',
    name: 'Seitán (Proteína de Trigo)',
    aliases: ['seitan', 'seitán'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥩',
    per100g: { calories: 140, protein: 24.5, carbs: 4.0, fats: 2.0 },
    thyroidFriendly: true,
  },
  {
    id: 'soja-texturizada',
    name: 'Soja Texturizada (Fina / Gruesa - Seca)',
    aliases: ['soja texturizada', 'proteina de soja', 'carne picada vegetal'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 40,
    icon: '🧆',
    per100g: { calories: 350, protein: 50.0, carbs: 20.0, fats: 1.5 },
    thyroidFriendly: true,
  },
  {
    id: 'heura-proteina-vegetal',
    name: 'Heura / Bocados de Proteína Vegetal',
    aliases: ['heura', 'bocados vegetales', 'pollo vegetal'],
    category: 'lacteos_huevos',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🌱',
    per100g: { calories: 136, protein: 19.0, carbs: 1.8, fats: 5.0 },
    thyroidFriendly: true,
  },
  {
    id: 'levadura-nutricional',
    name: 'Levadura Nutricional en Copos',
    aliases: ['levadura nutricional', 'queso vegano en polvo'],
    category: 'lacteos_huevos',
    defaultUnit: 'cucharada',
    defaultAmount: 2,
    icon: '🌾',
    per100g: { calories: 340, protein: 48.0, carbs: 18.0, fats: 4.0 },
    perTablespoon: { calories: 34, protein: 4.8, carbs: 1.8, fats: 0.4 },
    thyroidFriendly: true,
    thyroidNote: 'Bomba natural de complejo vitamínico B y zinc.',
  }
];
