import { FoodDatabaseItem } from './types';

export const FISH_SEAFOOD_DATABASE: FoodDatabaseItem[] = [
  {
    id: 'salmon-fresco',
    name: 'Salmón Fresco (Lomo / Rodaja)',
    aliases: ['salmon', 'salmón', 'lomo de salmon', 'rodaja de salmon'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🐟',
    per100g: { calories: 206, protein: 20.4, carbs: 0, fats: 13.4 },
    thyroidFriendly: true,
    thyroidNote: 'Excelente fuente de Omega-3 EPA/DHA antiinflamatorio y selenio.',
  },
  {
    id: 'salmon-ahumado',
    name: 'Salmón Ahumado',
    aliases: ['salmon ahumado', 'salmón ahumado', 'tostada de salmon'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 60,
    icon: '🐟',
    per100g: { calories: 180, protein: 21.5, carbs: 0, fats: 10.5 },
    thyroidFriendly: true,
  },
  {
    id: 'atun-fresco-lomo',
    name: 'Atún Rojo / Lomo de Atún Fresco',
    aliases: ['lomo de atun', 'atun fresco', 'tataki de atun', 'atún'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🐟',
    per100g: { calories: 144, protein: 23.3, carbs: 0, fats: 4.9 },
    thyroidFriendly: true,
  },
  {
    id: 'atun-natural',
    name: 'Atún al Natural (Lata)',
    aliases: ['atun', 'lata de atun', 'atun al natural', 'bonito'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🐟',
    per100g: { calories: 105, protein: 24.0, carbs: 0, fats: 1.0 },
    thyroidFriendly: true,
  },
  {
    id: 'atun-aceite-oliva',
    name: 'Atún en Aceite de Oliva (Escurrido)',
    aliases: ['atun en aceite', 'bonito en aceite'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🐟',
    per100g: { calories: 185, protein: 24.0, carbs: 0, fats: 10.0 },
    thyroidFriendly: true,
  },
  {
    id: 'bonito-norte',
    name: 'Bonito del Norte',
    aliases: ['bonito del norte', 'bonito fresco'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🐟',
    per100g: { calories: 138, protein: 24.5, carbs: 0, fats: 4.5 },
    thyroidFriendly: true,
  },
  {
    id: 'merluza-pescado-blanco',
    name: 'Merluza Fresca / Congelada',
    aliases: ['merluza', 'filete de merluza', 'lomos de merluza', 'pescado blanco'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 180,
    icon: '🐟',
    per100g: { calories: 75, protein: 16.8, carbs: 0, fats: 0.8 },
    thyroidFriendly: true,
    thyroidNote: 'Proteína ligera digestiva con moderado yodo natural.',
  },
  {
    id: 'bacalao',
    name: 'Bacalao Fresco / Desalado',
    aliases: ['bacalao', 'lomo de bacalao'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 180,
    icon: '🐟',
    per100g: { calories: 82, protein: 18.0, carbs: 0, fats: 0.7 },
    thyroidFriendly: true,
    thyroidNote: 'Aporte natural de yodo indispensable para la glándula tiroides.',
  },
  {
    id: 'dorada-lubina',
    name: 'Dorada / Lubina / Corvina',
    aliases: ['dorada', 'lubina', 'corvina'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 180,
    icon: '🐟',
    per100g: { calories: 98, protein: 19.0, carbs: 0, fats: 2.5 },
    thyroidFriendly: true,
  },
  {
    id: 'lenguado-gallo',
    name: 'Lenguado / Gallo',
    aliases: ['lenguado', 'gallo', 'filete de lenguado'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 180,
    icon: '🐟',
    per100g: { calories: 80, protein: 17.0, carbs: 0, fats: 1.2 },
    thyroidFriendly: true,
  },
  {
    id: 'rape',
    name: 'Rape (Lomo / Cola)',
    aliases: ['rape', 'cola de rape'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 180,
    icon: '🐟',
    per100g: { calories: 85, protein: 18.5, carbs: 0, fats: 1.0 },
    thyroidFriendly: true,
  },
  {
    id: 'rodaballo',
    name: 'Rodaballo',
    aliases: ['rodaballo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 180,
    icon: '🐟',
    per100g: { calories: 102, protein: 16.5, carbs: 0, fats: 3.5 },
    thyroidFriendly: true,
  },
  {
    id: 'trucha',
    name: 'Trucha Fresca (Asalmonada)',
    aliases: ['trucha', 'trucha asalmonada'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🐟',
    per100g: { calories: 135, protein: 19.5, carbs: 0, fats: 6.0 },
    thyroidFriendly: true,
  },
  {
    id: 'sardinas-frescas',
    name: 'Sardinas Frescas a la Plancha',
    aliases: ['sardinas', 'sardina', 'sardinillas'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🐟',
    per100g: { calories: 155, protein: 19.8, carbs: 0, fats: 8.5 },
    thyroidFriendly: true,
    thyroidNote: 'Pescado azul bajo en mercurio, rico en Omega-3, calcio y vitamina D.',
  },
  {
    id: 'sardinas-lata',
    name: 'Sardinas en Lata (Aceite de Oliva)',
    aliases: ['sardinas en lata', 'sardinas lata'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 85,
    icon: '🥫',
    per100g: { calories: 208, protein: 24.0, carbs: 0, fats: 12.5 },
    thyroidFriendly: true,
  },
  {
    id: 'caballa',
    name: 'Caballa Fresca o en Conserva',
    aliases: ['caballa', 'verdel'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 120,
    icon: '🐟',
    per100g: { calories: 168, protein: 20.0, carbs: 0, fats: 9.8 },
    thyroidFriendly: true,
  },
  {
    id: 'boquerones-anchoas',
    name: 'Boquerones / Anchoas en Aceite',
    aliases: ['boquerones', 'anchoas', 'anchoa'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 50,
    icon: '🐟',
    per100g: { calories: 210, protein: 28.0, carbs: 0, fats: 11.0 },
    thyroidFriendly: true,
  },
  {
    id: 'pez-espada-emperador',
    name: 'Pez Espada / Emperador',
    aliases: ['emperador', 'pez espada'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🐟',
    per100g: { calories: 125, protein: 20.0, carbs: 0, fats: 4.8 },
    thyroidFriendly: true,
  },
  {
    id: 'gambas-langostinos',
    name: 'Gambas / Langostinos Cocidos o Plancha',
    aliases: ['gambas', 'langostinos', 'camarones', 'gambones', 'cigalas'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🦐',
    per100g: { calories: 95, protein: 20.5, carbs: 0.8, fats: 1.1 },
    thyroidFriendly: true,
    thyroidNote: 'Potente fuente de zinc, selenio y yodo marino.',
  },
  {
    id: 'sepia-calamar',
    name: 'Sepia / Calamar / Chipirones / Choco',
    aliases: ['sepia', 'calamar', 'calamares', 'choco', 'chipirones'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 180,
    icon: '🦑',
    per100g: { calories: 85, protein: 17.5, carbs: 1.2, fats: 1.1 },
    thyroidFriendly: true,
  },
  {
    id: 'pulpo-cocido',
    name: 'Pulpo Cocido (A la Gallega / Brasa)',
    aliases: ['pulpo', 'pulpo cocido', 'pata de pulpo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🐙',
    per100g: { calories: 86, protein: 18.2, carbs: 1.5, fats: 0.9 },
    thyroidFriendly: true,
  },
  {
    id: 'mejillones',
    name: 'Mejillones al Vapor / Escabeche',
    aliases: ['mejillones', 'mejillon'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🦪',
    per100g: { calories: 86, protein: 12.0, carbs: 3.7, fats: 2.2 },
    thyroidFriendly: true,
    thyroidNote: 'Campeón en hierro y selenio biodisponible.',
  },
  {
    id: 'berberechos-almejas',
    name: 'Berberechos / Almejas al Vapor o en Lata',
    aliases: ['berberechos', 'almejas', 'coquinas', 'chirlas'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🦪',
    per100g: { calories: 64, protein: 13.5, carbs: 1.5, fats: 0.6 },
    thyroidFriendly: true,
  },
  {
    id: 'ostras-vieiras',
    name: 'Ostras / Vieiras',
    aliases: ['ostras', 'vieiras', 'zamburiñas'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 120,
    icon: '🦪',
    per100g: { calories: 70, protein: 9.5, carbs: 4.0, fats: 1.8 },
    thyroidFriendly: true,
    thyroidNote: 'La fuente marina más rica en zinc de toda la naturaleza.',
  },
  {
    id: 'cangrejo-bogavante',
    name: 'Cangrejo / Bogavante / Langosta',
    aliases: ['cangrejo', 'bogavante', 'langosta', 'buey de mar', 'centollo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🦀',
    per100g: { calories: 90, protein: 19.0, carbs: 0, fats: 1.2 },
    thyroidFriendly: true,
  },
  {
    id: 'gulas-surimi',
    name: 'Gulas / Palitos de Cangrejo (Surimi)',
    aliases: ['gulas', 'palitos de cangrejo', 'surimi'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🦀',
    per100g: { calories: 110, protein: 10.0, carbs: 12.0, fats: 2.0 },
    thyroidFriendly: true,
  }
];
