import { FoodDatabaseItem } from './types';

export const FRUITS_DATABASE: FoodDatabaseItem[] = [
  {
    id: 'platano',
    name: 'Plátano / Banana',
    aliases: ['platano', 'plátano', 'banana', 'guineo'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 1,
    icon: '🍌',
    per100g: { calories: 89, protein: 1.1, carbs: 22.8, fats: 0.3 },
    perUnit: { calories: 105, protein: 1.3, carbs: 27.0, fats: 0.4 },
    thyroidFriendly: true,
    thyroidNote: 'Potasio, vitamina B6 y triptófano regulador del ánimo y tiroides.',
  },
  {
    id: 'manzana',
    name: 'Manzana (Fuji / Golden / Gala / Granny Smith)',
    aliases: ['manzana', 'manzana fuji', 'manzana golden'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 1,
    icon: '🍎',
    per100g: { calories: 52, protein: 0.3, carbs: 13.8, fats: 0.2 },
    perUnit: { calories: 80, protein: 0.4, carbs: 21.0, fats: 0.3 },
    thyroidFriendly: true,
    thyroidNote: 'Pectina prebiótica para el tránsito intestinal.',
  },
  {
    id: 'pera',
    name: 'Pera (Conferencia / Blanquilla / Williams)',
    aliases: ['pera', 'pera conferencia'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 1,
    icon: '🍐',
    per100g: { calories: 57, protein: 0.4, carbs: 15.2, fats: 0.1 },
    perUnit: { calories: 85, protein: 0.6, carbs: 22.8, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'arandanos-rojos-moras',
    name: 'Arándanos / Frutos Rojos / Moras / Grosellas',
    aliases: ['arandanos', 'arándanos', 'frutos rojos', 'moras', 'grosellas'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🫐',
    per100g: { calories: 57, protein: 0.7, carbs: 14.5, fats: 0.3 },
    thyroidFriendly: true,
    thyroidNote: 'Antocianinas que protegen el tejido tiroideo del estrés oxidativo.',
  },
  {
    id: 'fresas-frambuesas',
    name: 'Fresas / Fresones / Frambuesas',
    aliases: ['fresas', 'fresa', 'fresones', 'frambuesas'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍓',
    per100g: { calories: 33, protein: 0.7, carbs: 7.7, fats: 0.3 },
    thyroidFriendly: true,
  },
  {
    id: 'naranja-mandarina',
    name: 'Naranja / Mandarina / Clementina',
    aliases: ['naranja', 'mandarina', 'mandarinas', 'clementina', 'zumo de naranja'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 1,
    icon: '🍊',
    per100g: { calories: 47, protein: 0.9, carbs: 11.8, fats: 0.1 },
    perUnit: { calories: 65, protein: 1.2, carbs: 16.0, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'limon-lima',
    name: 'Limón / Lima (Zumo o Pieza)',
    aliases: ['limon', 'limón', 'lima', 'zumo de limon'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 1,
    icon: '🍋',
    per100g: { calories: 29, protein: 1.1, carbs: 9.3, fats: 0.3 },
    perUnit: { calories: 15, protein: 0.5, carbs: 4.5, fats: 0.1 },
    thyroidFriendly: true,
  },
  {
    id: 'kiwi',
    name: 'Kiwi (Verde / Gold)',
    aliases: ['kiwi', 'kiwi gold', 'kiwi verde'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 1,
    icon: '🥝',
    per100g: { calories: 61, protein: 1.1, carbs: 14.7, fats: 0.5 },
    perUnit: { calories: 46, protein: 0.8, carbs: 11.0, fats: 0.4 },
    thyroidFriendly: true,
    thyroidNote: 'Enzima actinidina que mejora la digestión de proteínas.',
  },
  {
    id: 'pina-natural',
    name: 'Piña Natural Fresca',
    aliases: ['piña', 'pina', 'ananas'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍍',
    per100g: { calories: 50, protein: 0.5, carbs: 13.1, fats: 0.1 },
    thyroidFriendly: true,
    thyroidNote: 'Bromelaína antiinflamatoria digestiva.',
  },
  {
    id: 'sandia-melon',
    name: 'Sandía / Melón (Piel de Sapo / Cantaloupe)',
    aliases: ['sandia', 'sandía', 'melon', 'melón'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 250,
    icon: '🍉',
    per100g: { calories: 30, protein: 0.6, carbs: 7.6, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'melocoton-nectarina',
    name: 'Melocotón / Nectarina / Albaricoque / Paraguayo',
    aliases: ['melocoton', 'nectarina', 'albaricoque', 'paraguayo', 'durazno', 'damasco'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 1,
    icon: '🍑',
    per100g: { calories: 39, protein: 0.9, carbs: 9.5, fats: 0.3 },
    perUnit: { calories: 58, protein: 1.3, carbs: 14.2, fats: 0.4 },
    thyroidFriendly: true,
  },
  {
    id: 'cerezas-picotas',
    name: 'Cerezas / Picotas',
    aliases: ['cerezas', 'picotas', 'cereza'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 120,
    icon: '🍒',
    per100g: { calories: 63, protein: 1.1, carbs: 16.0, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'ciruelas',
    name: 'Ciruelas (Rojas / Amarillas)',
    aliases: ['ciruela', 'ciruelas'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 2,
    icon: '🫐',
    per100g: { calories: 46, protein: 0.7, carbs: 11.4, fats: 0.3 },
    perUnit: { calories: 30, protein: 0.5, carbs: 7.4, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'mango-papaya',
    name: 'Mango / Papaya Fresca',
    aliases: ['mango', 'papaya'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥭',
    per100g: { calories: 60, protein: 0.8, carbs: 15.0, fats: 0.4 },
    thyroidFriendly: true,
    thyroidNote: 'Rico en vitamina A y papaína digestiva.',
  },
  {
    id: 'uvas',
    name: 'Uvas Blancas / Negras',
    aliases: ['uvas', 'uva'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 120,
    icon: '🍇',
    per100g: { calories: 69, protein: 0.7, carbs: 18.1, fats: 0.2 },
    thyroidFriendly: true,
    thyroidNote: 'Resveratrol antioxidante antienvejecimiento celular.',
  },
  {
    id: 'higos-brevas',
    name: 'Higos Frescos / Brevas',
    aliases: ['higos', 'higo', 'brevas'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 2,
    icon: '🫐',
    per100g: { calories: 74, protein: 0.8, carbs: 19.2, fats: 0.3 },
    perUnit: { calories: 37, protein: 0.4, carbs: 9.6, fats: 0.15 },
    thyroidFriendly: true,
  },
  {
    id: 'granada',
    name: 'Granada (Granos)',
    aliases: ['granada'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🍎',
    per100g: { calories: 83, protein: 1.7, carbs: 18.7, fats: 1.2 },
    thyroidFriendly: true,
  },
  {
    id: 'datiles-medjool',
    name: 'Dátiles Medjool / Naturales',
    aliases: ['datiles', 'dátiles', 'datil', 'medjool'],
    category: 'frutas',
    defaultUnit: 'ud',
    defaultAmount: 2,
    icon: '🌴',
    per100g: { calories: 277, protein: 1.8, carbs: 75.0, fats: 0.2 },
    perUnit: { calories: 66, protein: 0.4, carbs: 18.0, fats: 0.05 },
    thyroidFriendly: true,
  },
  {
    id: 'coco-fresco-agua-coco',
    name: 'Coco Fresco / Agua de Coco',
    aliases: ['coco', 'agua de coco', 'coco rallado'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 50,
    icon: '🥥',
    per100g: { calories: 354, protein: 3.3, carbs: 15.2, fats: 33.5 },
    thyroidFriendly: true,
  },
  {
    id: 'maracuya-pitahaya',
    name: 'Maracuyá / Pitahaya / Guayaba / Fruta de la Pasión',
    aliases: ['maracuya', 'maracuyá', 'pitahaya', 'dragon fruit', 'guayaba'],
    category: 'frutas',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🍈',
    per100g: { calories: 60, protein: 1.5, carbs: 13.0, fats: 0.5 },
    thyroidFriendly: true,
  }
];
