import { FoodDatabaseItem } from './types';

export const GRAINS_TUBERS_DATABASE: FoodDatabaseItem[] = [
  {
    id: 'arroz-blanco-cocido',
    name: 'Arroz Blanco Cocido (Basmati / Redondo / Jazmín)',
    aliases: ['arroz', 'arroz blanco', 'arroz basmati', 'arroz jazmin', 'arroz bomba', 'arroz sushi'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍚',
    per100g: { calories: 130, protein: 2.7, carbs: 28.2, fats: 0.3 },
    thyroidFriendly: true,
  },
  {
    id: 'arroz-integral-cocido',
    name: 'Arroz Integral Cocido',
    aliases: ['arroz integral', 'arroz salvaje', 'arroz rojo'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍚',
    per100g: { calories: 112, protein: 2.6, carbs: 23.5, fats: 0.9 },
    thyroidFriendly: true,
    thyroidNote: 'Carbohidrato complejo de absorción lenta rico en magnesio.',
  },
  {
    id: 'arroz-crudo',
    name: 'Arroz Crudo / Seco (Cualquier variedad)',
    aliases: ['arroz crudo', 'arroz seco'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 60,
    icon: '🍚',
    per100g: { calories: 360, protein: 7.5, carbs: 78.0, fats: 0.8 },
    thyroidFriendly: true,
  },
  {
    id: 'avena-copos',
    name: 'Copos de Avena Integral / Porridge',
    aliases: ['avena', 'copos de avena', 'porridge', 'gachas de avena', 'harina de avena'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 50,
    icon: '🥣',
    per100g: { calories: 375, protein: 13.5, carbs: 60.0, fats: 7.0 },
    thyroidFriendly: true,
    thyroidNote: 'Betaglucanos que regulan el colesterol y la glucemia.',
  },
  {
    id: 'salvado-avena-trigo',
    name: 'Salvado de Avena / Salvado de Trigo',
    aliases: ['salvado', 'salvado de avena', 'salvado de trigo'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 25,
    icon: '🌾',
    per100g: { calories: 246, protein: 17.0, carbs: 45.0, fats: 7.0 },
    thyroidFriendly: true,
  },
  {
    id: 'patata-cocida',
    name: 'Patata Cocida / Al Horno / Vapor',
    aliases: ['patata', 'patatas', 'papa', 'papas', 'patata cocida', 'patata asada', 'pure de patatas'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🥔',
    per100g: { calories: 77, protein: 2.0, carbs: 17.5, fats: 0.1 },
    perUnit: { calories: 154, protein: 4.0, carbs: 35.0, fats: 0.2 },
    thyroidFriendly: true,
    thyroidNote: 'Excelente almidón resistente si se deja enfriar 24h tras cocinar.',
  },
  {
    id: 'patatas-fritas',
    name: 'Patatas Fritas Caseras (Aceite de Oliva)',
    aliases: ['patatas fritas', 'papas fritas'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🍟',
    per100g: { calories: 290, protein: 3.5, carbs: 38.0, fats: 14.0 },
    thyroidFriendly: true,
  },
  {
    id: 'boniato-batata',
    name: 'Boniato / Batata Asada o Cocida / Camote',
    aliases: ['boniato', 'batata', 'camote', 'boniato asado'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 180,
    icon: '🍠',
    per100g: { calories: 86, protein: 1.6, carbs: 20.1, fats: 0.1 },
    perUnit: { calories: 155, protein: 2.9, carbs: 36.2, fats: 0.2 },
    thyroidFriendly: true,
    thyroidNote: 'Riquísimo en betacaroteno provitamina A y potasio.',
  },
  {
    id: 'yuca-mandioca',
    name: 'Yuca / Mandioca Cocida',
    aliases: ['yuca', 'mandioca', 'tapioca'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥔',
    per100g: { calories: 160, protein: 1.4, carbs: 38.0, fats: 0.3 },
    thyroidFriendly: true,
  },
  {
    id: 'pasta-cocida',
    name: 'Pasta de Trigo Cocida (Espaguetis / Macarrones)',
    aliases: ['pasta', 'espaguetis', 'macarrones', 'plumas', 'fideos', 'tallarines', 'pasta cocida'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍝',
    per100g: { calories: 131, protein: 5.0, carbs: 25.0, fats: 1.1 },
    thyroidFriendly: true,
  },
  {
    id: 'pasta-integral-cocida',
    name: 'Pasta 100% Integral Cocida',
    aliases: ['pasta integral', 'espaguetis integrales', 'macarrones integrales'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍝',
    per100g: { calories: 124, protein: 5.3, carbs: 26.5, fats: 0.5 },
    thyroidFriendly: true,
  },
  {
    id: 'pasta-cruda-seca',
    name: 'Pasta Seca / Cruda (Cualquier tipo)',
    aliases: ['pasta cruda', 'pasta seca', 'espaguetis crudos', 'macarrones crudos'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 70,
    icon: '🍝',
    per100g: { calories: 360, protein: 12.5, carbs: 72.0, fats: 1.5 },
    thyroidFriendly: true,
  },
  {
    id: 'fideos-arroz-ramen-udon',
    name: 'Fideos de Arroz / Fideos Udon / Ramen Cocidos',
    aliases: ['fideos de arroz', 'udon', 'ramen', 'noodles', 'fideos chinos'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍜',
    per100g: { calories: 109, protein: 1.8, carbs: 24.0, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'noquis-patata',
    name: 'Ñoquis de Patata (Gnocchi)',
    aliases: ['ñoquis', 'gnocchi', 'noquis'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 180,
    icon: '🥟',
    per100g: { calories: 140, protein: 3.5, carbs: 30.0, fats: 0.8 },
    thyroidFriendly: true,
  },
  {
    id: 'quinoa-cocida',
    name: 'Quinoa Cocida',
    aliases: ['quinoa', 'quinua'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🌾',
    per100g: { calories: 120, protein: 4.4, carbs: 21.3, fats: 1.9 },
    thyroidFriendly: true,
    thyroidNote: 'Pseudocereal sin gluten con todos los aminoácidos.',
  },
  {
    id: 'cuscus-semola',
    name: 'Cuscús / Sémola de Trigo Cocida',
    aliases: ['cuscus', 'cuscús', 'semola', 'sémola'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍚',
    per100g: { calories: 112, protein: 3.8, carbs: 23.2, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'trigo-sarraceno-alforfon',
    name: 'Trigo Sarraceno / Alforfón Cocido',
    aliases: ['trigo sarraceno', 'alforfon', 'alforfón'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🌾',
    per100g: { calories: 92, protein: 3.4, carbs: 19.9, fats: 0.6 },
    thyroidFriendly: true,
  },
  {
    id: 'pan-integral',
    name: 'Pan 100% Integral / Masa Madre',
    aliases: ['pan integral', 'pan de centeno', 'pan masa madre', 'pan espelta', 'tostada integral'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 60,
    icon: '🍞',
    per100g: { calories: 247, protein: 9.0, carbs: 41.0, fats: 3.5 },
    thyroidFriendly: true,
  },
  {
    id: 'pan-blanco',
    name: 'Pan Blanco de Barra / Baguette',
    aliases: ['pan blanco', 'pan de barra', 'baguette', 'pan'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 60,
    icon: '🥖',
    per100g: { calories: 265, protein: 8.5, carbs: 52.0, fats: 1.2 },
    thyroidFriendly: true,
  },
  {
    id: 'pan-molde-integral',
    name: 'Pan de Molde Integral / Tostada',
    aliases: ['pan de molde', 'pan de molde integral', 'sandwich'],
    category: 'legumbres_cereales',
    defaultUnit: 'ud',
    defaultAmount: 2,
    icon: '🍞',
    per100g: { calories: 235, protein: 9.5, carbs: 40.0, fats: 3.0 },
    perUnit: { calories: 68, protein: 2.8, carbs: 11.6, fats: 0.9 },
    thyroidFriendly: true,
  },
  {
    id: 'tortilla-trigo-maiz',
    name: 'Tortillas de Trigo / Maíz (Fajitas / Wraps)',
    aliases: ['tortilla fajita', 'wrap', 'tortilla de trigo', 'tortilla de maiz', 'tacos'],
    category: 'legumbres_cereales',
    defaultUnit: 'ud',
    defaultAmount: 2,
    icon: '🫓',
    per100g: { calories: 290, protein: 8.0, carbs: 50.0, fats: 6.0 },
    perUnit: { calories: 120, protein: 3.3, carbs: 20.5, fats: 2.5 },
    thyroidFriendly: true,
  },
  {
    id: 'tortitas-arroz-maiz',
    name: 'Tortitas de Arroz / Maíz Inflado',
    aliases: ['tortitas de arroz', 'tortitas de maiz', 'tortitas arroz'],
    category: 'legumbres_cereales',
    defaultUnit: 'ud',
    defaultAmount: 2,
    icon: '🍘',
    per100g: { calories: 385, protein: 8.0, carbs: 82.0, fats: 2.5 },
    perUnit: { calories: 28, protein: 0.6, carbs: 6.0, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'harina-trigo-avena-maiz',
    name: 'Harina (Trigo / Avena / Espelta / Maíz)',
    aliases: ['harina', 'harina de trigo', 'harina de avena', 'maicena', 'harina de espelta'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 50,
    icon: '🌾',
    per100g: { calories: 364, protein: 11.0, carbs: 74.0, fats: 1.5 },
    thyroidFriendly: true,
  },
  {
    id: 'harina-almendra-garbanzo',
    name: 'Harina de Almendra / Harina de Garbanzo',
    aliases: ['harina de almendra', 'harina de garbanzo', 'harina sin gluten'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 40,
    icon: '🌾',
    per100g: { calories: 575, protein: 21.5, carbs: 10.0, fats: 50.0 },
    thyroidFriendly: true,
  },
  {
    id: 'pan-pita-naan',
    name: 'Pan Pita / Pan Naan',
    aliases: ['pan pita', 'pita', 'pan naan', 'naan'],
    category: 'legumbres_cereales',
    defaultUnit: 'ud',
    defaultAmount: 1,
    icon: '🫓',
    per100g: { calories: 275, protein: 9.0, carbs: 54.0, fats: 1.8 },
    perUnit: { calories: 165, protein: 5.4, carbs: 32.4, fats: 1.1 },
    thyroidFriendly: true,
  }
];
