import { FoodDatabaseItem } from './types';

export const LEGUMES_DATABASE: FoodDatabaseItem[] = [
  {
    id: 'lentejas-cocidas',
    name: 'Lentejas Cocidas / Estofadas',
    aliases: ['lentejas', 'lentejas cocidas', 'lenteja', 'lentejas con verduras', 'lentejas pardinas'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🧆',
    per100g: { calories: 116, protein: 9.0, carbs: 17.0, fats: 0.4 },
    thyroidFriendly: true,
    thyroidNote: 'Ricas en hierro vegetal no hemo, zinc, folatos y fibra saciante.',
  },
  {
    id: 'lentejas-secas',
    name: 'Lentejas Secas / Crudas / Lentejas Rojas',
    aliases: ['lentejas secas', 'lentejas rojas', 'lenteja seca'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 70,
    icon: '🧆',
    per100g: { calories: 335, protein: 24.5, carbs: 52.0, fats: 1.2 },
    thyroidFriendly: true,
  },
  {
    id: 'garbanzos-cocidos',
    name: 'Garbanzos Cocidos',
    aliases: ['garbanzos', 'garbanzo', 'garbanzos cocidos', 'garbanzos de bote'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🧆',
    per100g: { calories: 130, protein: 7.5, carbs: 18.5, fats: 2.6 },
    thyroidFriendly: true,
  },
  {
    id: 'garbanzos-secos',
    name: 'Garbanzos Secos / Crudos',
    aliases: ['garbanzos secos', 'garbanzo seco'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 70,
    icon: '🧆',
    per100g: { calories: 364, protein: 19.3, carbs: 60.6, fats: 6.0 },
    thyroidFriendly: true,
  },
  {
    id: 'hummus-tradicional',
    name: 'Hummus Tradicional de Garbanzo',
    aliases: ['hummus', 'humus', 'crema de garbanzo', 'pate de garbanzo'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 60,
    icon: '🥣',
    per100g: { calories: 177, protein: 5.5, carbs: 14.0, fats: 10.0 },
    perTablespoon: { calories: 45, protein: 1.4, carbs: 3.5, fats: 2.5 },
    thyroidFriendly: true,
  },
  {
    id: 'alubias-cocidas',
    name: 'Alubias / Judías Blancas / Pintas Cocidas',
    aliases: ['alubias', 'judias blancas', 'judias pintas', 'fabes', 'frijoles', 'alubias cocidas'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🧆',
    per100g: { calories: 110, protein: 7.8, carbs: 16.5, fats: 0.5 },
    thyroidFriendly: true,
  },
  {
    id: 'frijoles-negros',
    name: 'Frijoles Negros / Alubias Negras Cocidas',
    aliases: ['frijoles negros', 'alubias negras', 'porotos negros'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🧆',
    per100g: { calories: 120, protein: 8.5, carbs: 19.0, fats: 0.5 },
    thyroidFriendly: true,
  },
  {
    id: 'edamame',
    name: 'Edamame (Habas de Soja Tiernas Cocidas)',
    aliases: ['edamame', 'vainas de soja'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🫛',
    per100g: { calories: 121, protein: 11.9, carbs: 8.9, fats: 5.2 },
    thyroidFriendly: true,
  },
  {
    id: 'guisantes',
    name: 'Guisantes Tiernos Cocidos / Salteados',
    aliases: ['guisantes', 'arvejas', 'guisantes con jamon'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🟢',
    per100g: { calories: 81, protein: 5.4, carbs: 14.5, fats: 0.4 },
    thyroidFriendly: true,
  },
  {
    id: 'habas-frescas-cocidas',
    name: 'Habas Tiernas Cocidas',
    aliases: ['habas', 'habas tiernas', 'habitas'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🫛',
    per100g: { calories: 88, protein: 8.0, carbs: 12.0, fats: 0.7 },
    thyroidFriendly: true,
  },
  {
    id: 'altramuces',
    name: 'Altramuces / Chocho (Encurtido)',
    aliases: ['altramuces', 'altramuz', 'chochos'],
    category: 'legumbres_cereales',
    defaultUnit: 'g',
    defaultAmount: 80,
    icon: '🧆',
    per100g: { calories: 119, protein: 15.6, carbs: 7.1, fats: 2.9 },
    thyroidFriendly: true,
  }
];
