import { FoodDatabaseItem } from './types';

export const MEATS_DATABASE: FoodDatabaseItem[] = [
  {
    id: 'pechuga-pollo',
    name: 'Pechuga de Pollo',
    aliases: ['pollo', 'pechuga', 'pechuga de pollo', 'filete de pollo', 'pollo a la plancha'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍗',
    per100g: { calories: 120, protein: 23.5, carbs: 0, fats: 2.6 },
    thyroidFriendly: true,
    thyroidNote: 'Excelente fuente de L-tirosina para fabricar hormonas T3 y T4.',
  },
  {
    id: 'muslo-pollo',
    name: 'Muslo / Contramuslo de Pollo',
    aliases: ['muslo de pollo', 'contramuslo', 'pollo asado'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍗',
    per100g: { calories: 130, protein: 20.0, carbs: 0, fats: 5.5 },
    thyroidFriendly: true,
  },
  {
    id: 'alitas-pollo',
    name: 'Alitas de Pollo',
    aliases: ['alitas', 'alitas de pollo', 'alas de pollo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍗',
    per100g: { calories: 203, protein: 18.5, carbs: 0, fats: 14.2 },
    thyroidFriendly: true,
  },
  {
    id: 'pechuga-pavo',
    name: 'Pechuga de Pavo Fresca',
    aliases: ['pavo', 'pechuga de pavo', 'solomillo de pavo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🦃',
    per100g: { calories: 111, protein: 24.1, carbs: 0.5, fats: 1.6 },
    thyroidFriendly: true,
    thyroidNote: 'Proteína hipermagra con alto contenido en selenio.',
  },
  {
    id: 'muslo-pavo',
    name: 'Muslo de Pavo / Chuletas de Pavo',
    aliases: ['muslo de pavo', 'chuleta de pavo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🦃',
    per100g: { calories: 145, protein: 20.5, carbs: 0, fats: 7.0 },
    thyroidFriendly: true,
  },
  {
    id: 'fiambre-pavo-calidad',
    name: 'Pavo / Jamón Cocido Extra (>90%)',
    aliases: ['fiambre de pavo', 'jamon cocido', 'jamon york', 'pavo lonchas'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 80,
    icon: '🥪',
    per100g: { calories: 98, protein: 19.5, carbs: 1.2, fats: 1.5 },
    thyroidFriendly: true,
  },
  {
    id: 'ternera-magra',
    name: 'Ternera Magra / Solomillo / Bistec',
    aliases: ['ternera', 'carne de ternera', 'solomillo de ternera', 'bistec', 'filete de ternera'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥩',
    per100g: { calories: 143, protein: 22.0, carbs: 0, fats: 6.0 },
    thyroidFriendly: true,
    thyroidNote: 'Hierro hemo y zinc biodisponible, cofactores de la enzima deiodinasa tiroidea.',
  },
  {
    id: 'carne-picada-ternera',
    name: 'Carne Picada de Ternera Magra',
    aliases: ['carne picada', 'hamburguesa de ternera', 'picada ternera'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥩',
    per100g: { calories: 165, protein: 20.5, carbs: 0, fats: 9.0 },
    thyroidFriendly: true,
  },
  {
    id: 'entrecot-ternera',
    name: 'Entrecot / Chuletón de Ternera',
    aliases: ['entrecot', 'chuleton', 'lomo alto ternera', 'lomo bajo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🥩',
    per100g: { calories: 195, protein: 21.0, carbs: 0, fats: 12.5 },
    thyroidFriendly: true,
  },
  {
    id: 'higado-ternera',
    name: 'Hígado de Ternera',
    aliases: ['higado', 'higado de ternera', 'hígado'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 120,
    icon: '🥩',
    per100g: { calories: 135, protein: 21.0, carbs: 3.5, fats: 3.8 },
    thyroidFriendly: true,
    thyroidNote: 'La fuente más densa del planeta en vitamina A preformada, B12, cobre y hierro.',
  },
  {
    id: 'lomo-cerdo',
    name: 'Lomo de Cerdo Magro',
    aliases: ['lomo', 'lomo de cerdo', 'cinta de lomo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥩',
    per100g: { calories: 135, protein: 22.5, carbs: 0, fats: 4.8 },
    thyroidFriendly: true,
    thyroidNote: 'Rico en vitaminas B1 y B6 para la energía.',
  },
  {
    id: 'solomillo-cerdo',
    name: 'Solomillo de Cerdo',
    aliases: ['solomillo de cerdo', 'solomillo cerdo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥩',
    per100g: { calories: 125, protein: 22.8, carbs: 0, fats: 3.8 },
    thyroidFriendly: true,
  },
  {
    id: 'jamon-iberico',
    name: 'Jamón Ibérico / Serrano de Bellota',
    aliases: ['jamon', 'jamón', 'jamon serrano', 'jamon iberico', 'paleta iberica'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 50,
    icon: '🥓',
    per100g: { calories: 240, protein: 31.0, carbs: 0.5, fats: 13.0 },
    thyroidFriendly: true,
  },
  {
    id: 'secreto-presa-cerdo',
    name: 'Presa / Secreto Ibérico',
    aliases: ['secreto', 'presa', 'secreto iberico', 'presa iberica'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥩',
    per100g: { calories: 245, protein: 18.0, carbs: 0, fats: 19.0 },
    thyroidFriendly: true,
  },
  {
    id: 'costillas-cerdo',
    name: 'Costillas de Cerdo Asadas',
    aliases: ['costillas', 'costillas de cerdo', 'costillar'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🍖',
    per100g: { calories: 277, protein: 17.5, carbs: 0, fats: 23.0 },
    thyroidFriendly: true,
  },
  {
    id: 'lomo-embuchado',
    name: 'Lomo Embuchado Ibérico',
    aliases: ['lomo embuchado', 'caña de lomo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 50,
    icon: '🥓',
    per100g: { calories: 195, protein: 37.0, carbs: 1.0, fats: 5.0 },
    thyroidFriendly: true,
  },
  {
    id: 'conejo',
    name: 'Carne de Conejo',
    aliases: ['conejo', 'carne de conejo'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍗',
    per100g: { calories: 132, protein: 22.0, carbs: 0, fats: 4.8 },
    thyroidFriendly: true,
  },
  {
    id: 'cordero-chuletas',
    name: 'Chuletas / Pierna de Cordero',
    aliases: ['cordero', 'chuletas de cordero', 'pierna de cordero'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍖',
    per100g: { calories: 235, protein: 18.5, carbs: 0, fats: 18.0 },
    thyroidFriendly: true,
  },
  {
    id: 'pato-magret',
    name: 'Magret de Pato',
    aliases: ['pato', 'magret', 'magret de pato'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍗',
    per100g: { calories: 210, protein: 19.5, carbs: 0, fats: 14.5 },
    thyroidFriendly: true,
  },
  {
    id: 'ciervo-venado',
    name: 'Carne de Ciervo / Venado (Caza)',
    aliases: ['ciervo', 'venado', 'carne de caza'],
    category: 'carnes_pescados',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥩',
    per100g: { calories: 120, protein: 23.0, carbs: 0, fats: 2.5 },
    thyroidFriendly: true,
  }
];
