import { FoodDatabaseItem } from './types';

export const NUTS_OILS_DATABASE: FoodDatabaseItem[] = [
  {
    id: 'aove',
    name: 'Aceite de Oliva Virgen Extra (AOVE)',
    aliases: ['aceite', 'aove', 'aceite de oliva', 'aceite de oliva virgen extra', 'aceite oliva'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🫒',
    per100g: { calories: 884, protein: 0, carbs: 0, fats: 100 },
    perTablespoon: { calories: 90, protein: 0, carbs: 0, fats: 10 },
    thyroidFriendly: true,
    thyroidNote: 'Grasa monoinsaturada rey antiinflamatorio (ácido oleico y polifenoles).',
  },
  {
    id: 'aguacate',
    name: 'Aguacate Fresco / Palta',
    aliases: ['aguacate', 'palta', 'guacamole'],
    category: 'grasas_aceites',
    defaultUnit: 'g',
    defaultAmount: 75,
    icon: '🥑',
    per100g: { calories: 160, protein: 2.0, carbs: 8.5, fats: 14.7 },
    perUnit: { calories: 240, protein: 3.0, carbs: 12.8, fats: 22.0 },
    thyroidFriendly: true,
    thyroidNote: 'Grasas saludables y alto potasio para equilibrio electrolítico.',
  },
  {
    id: 'aceitunas',
    name: 'Aceitunas Verdes / Negras / Kalamata',
    aliases: ['aceitunas', 'olivas', 'aceitunas verdes', 'aceitunas negras'],
    category: 'grasas_aceites',
    defaultUnit: 'g',
    defaultAmount: 40,
    icon: '🫒',
    per100g: { calories: 145, protein: 1.0, carbs: 3.8, fats: 15.3 },
    thyroidFriendly: true,
  },
  {
    id: 'nueces-brasil',
    name: 'Nueces de Brasil (Castañas de Pará)',
    aliases: ['nueces de brasil', 'nuez de brasil', 'castañas de para'],
    category: 'grasas_aceites',
    defaultUnit: 'ud',
    defaultAmount: 2,
    icon: '🌰',
    per100g: { calories: 659, protein: 14.3, carbs: 12.3, fats: 67.1 },
    perUnit: { calories: 33, protein: 0.7, carbs: 0.6, fats: 3.3 },
    thyroidFriendly: true,
    thyroidNote: '¡EL REY DEL SELENIO! Con solo 1-2 nueces al día cubres el 100% de selenio para convertir T4 en T3 activa.',
  },
  {
    id: 'nueces-california',
    name: 'Nueces Comunes (de California / Pecanas)',
    aliases: ['nueces', 'nuez', 'nueces de california', 'pecanas'],
    category: 'grasas_aceites',
    defaultUnit: 'g',
    defaultAmount: 30,
    icon: '🌰',
    per100g: { calories: 654, protein: 15.2, carbs: 13.7, fats: 65.2 },
    thyroidFriendly: true,
    thyroidNote: 'Ricas en ácido alfa-linolénico (ALA vegetal) y polifenoles.',
  },
  {
    id: 'almendras',
    name: 'Almendras Crudas o Tostadas',
    aliases: ['almendras', 'almendra'],
    category: 'grasas_aceites',
    defaultUnit: 'g',
    defaultAmount: 30,
    icon: '🥜',
    per100g: { calories: 579, protein: 21.2, carbs: 21.6, fats: 49.9 },
    thyroidFriendly: true,
    thyroidNote: 'Vitamina E antioxidante y magnesio.',
  },
  {
    id: 'avellanas',
    name: 'Avellanas Tostadas o Naturales',
    aliases: ['avellanas', 'avellana'],
    category: 'grasas_aceites',
    defaultUnit: 'g',
    defaultAmount: 30,
    icon: '🌰',
    per100g: { calories: 628, protein: 15.0, carbs: 16.7, fats: 60.8 },
    thyroidFriendly: true,
  },
  {
    id: 'anacardos',
    name: 'Anacardos Naturales / Tostados',
    aliases: ['anacardos', 'anacardo', 'castañas de caju'],
    category: 'grasas_aceites',
    defaultUnit: 'g',
    defaultAmount: 30,
    icon: '🥜',
    per100g: { calories: 553, protein: 18.2, carbs: 30.2, fats: 43.8 },
    thyroidFriendly: true,
  },
  {
    id: 'pistachos',
    name: 'Pistachos Tostados',
    aliases: ['pistachos', 'pistacho'],
    category: 'grasas_aceites',
    defaultUnit: 'g',
    defaultAmount: 30,
    icon: '🥜',
    per100g: { calories: 562, protein: 20.2, carbs: 27.2, fats: 45.3 },
    thyroidFriendly: true,
  },
  {
    id: 'cacahuetes-mani',
    name: 'Cacahuetes / Maní Tostado',
    aliases: ['cacahuetes', 'cacahuete', 'mani', 'maní'],
    category: 'grasas_aceites',
    defaultUnit: 'g',
    defaultAmount: 30,
    icon: '🥜',
    per100g: { calories: 567, protein: 25.8, carbs: 16.1, fats: 49.2 },
    thyroidFriendly: true,
  },
  {
    id: 'crema-cacahuete-almendra',
    name: 'Crema de Cacahuete / Almendra 100%',
    aliases: ['crema de cacahuete', 'mantequilla de mani', 'crema de almendras', 'mantequilla de cacahuete'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🥜',
    per100g: { calories: 588, protein: 25.0, carbs: 20.0, fats: 50.0 },
    perTablespoon: { calories: 95, protein: 4.0, carbs: 3.2, fats: 8.0 },
    thyroidFriendly: true,
  },
  {
    id: 'tahini-pasta-sesamo',
    name: 'Tahini / Pasta de Sésamo 100%',
    aliases: ['tahini', 'tahin', 'pasta de sesamo'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🥣',
    per100g: { calories: 595, protein: 17.0, carbs: 21.0, fats: 54.0 },
    perTablespoon: { calories: 89, protein: 2.5, carbs: 3.1, fats: 8.1 },
    thyroidFriendly: true,
    thyroidNote: 'Calcio vegetal biodisponible, zinc y sesamol.',
  },
  {
    id: 'semillas-chia',
    name: 'Semillas de Chía',
    aliases: ['chia', 'semillas de chia', 'semillas de chía'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🌱',
    per100g: { calories: 486, protein: 16.5, carbs: 42.1, fats: 30.7 },
    perTablespoon: { calories: 49, protein: 1.7, carbs: 4.2, fats: 3.1 },
    thyroidFriendly: true,
    thyroidNote: 'Mucílagos solubles que alimentan la flora intestinal y Omega-3.',
  },
  {
    id: 'semillas-lino',
    name: 'Semillas de Lino Molidas (Linaza)',
    aliases: ['lino', 'semillas de lino', 'linaza'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🌱',
    per100g: { calories: 534, protein: 18.3, carbs: 28.9, fats: 42.2 },
    perTablespoon: { calories: 53, protein: 1.8, carbs: 2.9, fats: 4.2 },
    thyroidFriendly: true,
    thyroidNote: 'Lignanos reguladores hormonales y ácido alfa-linolénico.',
  },
  {
    id: 'pipas-calabaza',
    name: 'Pipas de Calabaza Peladas',
    aliases: ['pipas de calabaza', 'semillas de calabaza'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🎃',
    per100g: { calories: 559, protein: 30.2, carbs: 10.7, fats: 49.0 },
    perTablespoon: { calories: 56, protein: 3.0, carbs: 1.1, fats: 4.9 },
    thyroidFriendly: true,
    thyroidNote: 'Excepcional concentración de zinc y triptófano.',
  },
  {
    id: 'pipas-girasol-sesamo',
    name: 'Pipas de Girasol / Semillas de Sésamo / Cáñamo',
    aliases: ['pipas de girasol', 'sesamo', 'semillas de sesamo', 'semillas de cañamo'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🌻',
    per100g: { calories: 584, protein: 20.8, carbs: 20.0, fats: 51.5 },
    perTablespoon: { calories: 58, protein: 2.1, carbs: 2.0, fats: 5.1 },
    thyroidFriendly: true,
  },
  {
    id: 'aceite-coco',
    name: 'Aceite de Coco Virgen / MCT',
    aliases: ['aceite de coco', 'mct'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🥥',
    per100g: { calories: 862, protein: 0, carbs: 0, fats: 100 },
    perTablespoon: { calories: 86, protein: 0, carbs: 0, fats: 10 },
    thyroidFriendly: true,
    thyroidNote: 'Triglicéridos de cadena media que proporcionan energía rápida al hepatocito.',
  },
  {
    id: 'mantequilla-ghee',
    name: 'Mantequilla Tradicional / Ghee',
    aliases: ['mantequilla', 'ghee'],
    category: 'grasas_aceites',
    defaultUnit: 'cucharada',
    defaultAmount: 1,
    icon: '🧈',
    per100g: { calories: 717, protein: 0.8, carbs: 0.1, fats: 81.1 },
    perTablespoon: { calories: 72, protein: 0.1, carbs: 0.01, fats: 8.1 },
    thyroidFriendly: true,
    thyroidNote: 'Butirato regenerador del epitelio colónico.',
  }
];
