import { FoodDatabaseItem } from './types';

export const VEGETABLES_DATABASE: FoodDatabaseItem[] = [
  {
    id: 'calabacin',
    name: 'Calabacín a la Plancha o Vapor',
    aliases: ['calabacin', 'calabacín', 'zucchini'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🥒',
    per100g: { calories: 17, protein: 1.2, carbs: 3.1, fats: 0.3 },
    thyroidFriendly: true,
  },
  {
    id: 'zanahoria',
    name: 'Zanahoria Cocida o Cruda',
    aliases: ['zanahoria', 'zanahorias'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🥕',
    per100g: { calories: 41, protein: 0.9, carbs: 9.6, fats: 0.2 },
    perUnit: { calories: 25, protein: 0.6, carbs: 5.8, fats: 0.1 },
    thyroidFriendly: true,
    thyroidNote: 'Betacarotenos esenciales que apoyan la conversión hormonal.',
  },
  {
    id: 'tomate-natural',
    name: 'Tomate Natural / Ensalada / Cherry',
    aliases: ['tomate', 'tomate natural', 'tomate cherry', 'tomates'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍅',
    per100g: { calories: 18, protein: 0.9, carbs: 3.9, fats: 0.2 },
    perUnit: { calories: 22, protein: 1.1, carbs: 4.7, fats: 0.2 },
    thyroidFriendly: true,
    thyroidNote: 'Licopeno antioxidante celular.',
  },
  {
    id: 'tomate-triturado',
    name: 'Tomate Triturado / Salsa de Tomate Casera',
    aliases: ['tomate frito', 'tomate triturado', 'salsa de tomate'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🥫',
    per100g: { calories: 32, protein: 1.4, carbs: 5.5, fats: 0.3 },
    thyroidFriendly: true,
  },
  {
    id: 'tomate-seco',
    name: 'Tomate Seco / Deshidratado',
    aliases: ['tomate seco', 'tomates secos'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 20,
    icon: '🍅',
    per100g: { calories: 258, protein: 14.0, carbs: 55.0, fats: 3.0 },
    thyroidFriendly: true,
  },
  {
    id: 'espinacas-cocidas',
    name: 'Espinacas Cocidas / Salteadas',
    aliases: ['espinacas', 'espinaca', 'espinacas cocidas'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥬',
    per100g: { calories: 23, protein: 2.9, carbs: 3.6, fats: 0.4 },
    thyroidFriendly: true,
    thyroidNote: 'Consumir preferiblemente cocinadas para reducir oxalatos.',
  },
  {
    id: 'acelgas',
    name: 'Acelgas Cocidas',
    aliases: ['acelgas', 'acelga'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥬',
    per100g: { calories: 20, protein: 1.8, carbs: 3.7, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'brocoli-cocido',
    name: 'Brócoli al Vapor o Hervido',
    aliases: ['brocoli', 'brócoli', 'brocoli cocido'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥦',
    per100g: { calories: 34, protein: 2.8, carbs: 6.6, fats: 0.4 },
    thyroidFriendly: true,
    thyroidNote: 'Cocer al vapor o hervir >5 min inactiva los bociógenos (goitrógenos).',
  },
  {
    id: 'coliflor-cocida',
    name: 'Coliflor al Vapor / Asada',
    aliases: ['coliflor', 'coliflor cocida'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥦',
    per100g: { calories: 25, protein: 1.9, carbs: 5.0, fats: 0.3 },
    thyroidFriendly: true,
    thyroidNote: 'Cocer bien para inactivar compuestos bociógenos.',
  },
  {
    id: 'col-repollo-lombarda',
    name: 'Col / Repollo / Col Lombarda Cocida',
    aliases: ['repollo', 'col', 'lombarda', 'col morada'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥬',
    per100g: { calories: 25, protein: 1.3, carbs: 5.8, fats: 0.1 },
    thyroidFriendly: true,
  },
  {
    id: 'col-kale-rizada',
    name: 'Kale / Col Rizada Salteada',
    aliases: ['kale', 'col rizada'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🥬',
    per100g: { calories: 49, protein: 4.3, carbs: 8.8, fats: 0.9 },
    thyroidFriendly: true,
  },
  {
    id: 'coles-bruselas',
    name: 'Coles de Bruselas Cocidas',
    aliases: ['coles de bruselas', 'col de bruselas'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥬',
    per100g: { calories: 43, protein: 3.4, carbs: 9.0, fats: 0.3 },
    thyroidFriendly: true,
  },
  {
    id: 'pimiento-rojo-verde-amarillo',
    name: 'Pimiento Rojo / Verde / Amarillo',
    aliases: ['pimiento', 'pimiento rojo', 'pimiento verde', 'pimientos', 'pimiento asado'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🫑',
    per100g: { calories: 26, protein: 1.0, carbs: 6.0, fats: 0.3 },
    thyroidFriendly: true,
    thyroidNote: 'Bomba de vitamina C que potencia la absorción de hierro.',
  },
  {
    id: 'cebolla-cebolleta-puerro',
    name: 'Cebolla / Cebolleta / Puerro',
    aliases: ['cebolla', 'cebolleta', 'puerro', 'cebolla morada', 'chalotas'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 80,
    icon: '🧅',
    per100g: { calories: 40, protein: 1.1, carbs: 9.3, fats: 0.1 },
    thyroidFriendly: true,
    thyroidNote: 'Quercetina prebiótica y compuestos azufrados desintoxicantes.',
  },
  {
    id: 'ajo',
    name: 'Ajo Fresco',
    aliases: ['ajo', 'diente de ajo', 'ajos'],
    category: 'verduras',
    defaultUnit: 'ud',
    defaultAmount: 2,
    icon: '🧄',
    per100g: { calories: 149, protein: 6.4, carbs: 33.0, fats: 0.5 },
    perUnit: { calories: 4, protein: 0.2, carbs: 1.0, fats: 0.01 },
    thyroidFriendly: true,
    thyroidNote: 'Alicina inmunoestimulante y prebiótica.',
  },
  {
    id: 'esparragos-verdes-blancos',
    name: 'Espárragos Trigueros Verdes / Blancos',
    aliases: ['esparragos', 'espárragos', 'esparragos trigueros', 'esparragos verdes', 'esparragos blancos'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🌱',
    per100g: { calories: 20, protein: 2.2, carbs: 3.9, fats: 0.1 },
    thyroidFriendly: true,
  },
  {
    id: 'champinones-setas',
    name: 'Champiñones / Setas / Boletus / Shiitake',
    aliases: ['champinones', 'champiñones', 'setas', 'boletus', 'shiitake', 'portobello', 'girgolas'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍄',
    per100g: { calories: 22, protein: 3.1, carbs: 3.3, fats: 0.3 },
    thyroidFriendly: true,
    thyroidNote: 'Contienen selenio, cobre y betaglucanos inmunitarios.',
  },
  {
    id: 'berenjena',
    name: 'Berenjena Asada o Plancha',
    aliases: ['berenjena', 'berenjenas'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🍆',
    per100g: { calories: 25, protein: 1.0, carbs: 5.9, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'calabaza',
    name: 'Calabaza Asada o Cocida',
    aliases: ['calabaza', 'zapallo', 'crema de calabaza'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 200,
    icon: '🎃',
    per100g: { calories: 26, protein: 1.0, carbs: 6.5, fats: 0.1 },
    thyroidFriendly: true,
  },
  {
    id: 'judias-verdes',
    name: 'Judías Verdes / Vainas',
    aliases: ['judias verdes', 'judías verdes', 'vainas', 'ejotes'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🫛',
    per100g: { calories: 31, protein: 1.8, carbs: 7.0, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'lechuga-canongos-rucula',
    name: 'Lechuga / Canónigos / Rúcula / Mezclum',
    aliases: ['lechuga', 'ensalada', 'canónigos', 'rucula', 'rúcula', 'escarola', 'endivias', 'berros'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 80,
    icon: '🥗',
    per100g: { calories: 15, protein: 1.4, carbs: 2.9, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'pepino',
    name: 'Pepino Fresco',
    aliases: ['pepino', 'pepinillos'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🥒',
    per100g: { calories: 15, protein: 0.7, carbs: 3.6, fats: 0.1 },
    thyroidFriendly: true,
  },
  {
    id: 'alcachofas',
    name: 'Alcachofas Cocidas / Plancha',
    aliases: ['alcachofas', 'alcachofa', 'corazones de alcachofa'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 150,
    icon: '🥦',
    per100g: { calories: 47, protein: 3.3, carbs: 10.5, fats: 0.2 },
    thyroidFriendly: true,
    thyroidNote: 'Inulina prebiótica y cinarina protectora hepática.',
  },
  {
    id: 'apio-hinojo',
    name: 'Apio / Hinojo',
    aliases: ['apio', 'hinojo'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 80,
    icon: '🌱',
    per100g: { calories: 16, protein: 0.7, carbs: 3.0, fats: 0.2 },
    thyroidFriendly: true,
  },
  {
    id: 'remolacha-cocida',
    name: 'Remolacha Cocida',
    aliases: ['remolacha', 'betabel'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 100,
    icon: '🍠',
    per100g: { calories: 43, protein: 1.6, carbs: 9.6, fats: 0.2 },
    thyroidFriendly: true,
    thyroidNote: 'Nitratos naturales vasodilatadores y antioxidantes betalaínas.',
  },
  {
    id: 'jengibre-fresco',
    name: 'Jengibre Fresco Rallado',
    aliases: ['jengibre', 'kion'],
    category: 'verduras',
    defaultUnit: 'g',
    defaultAmount: 10,
    icon: '🫚',
    per100g: { calories: 80, protein: 1.8, carbs: 17.8, fats: 0.8 },
    thyroidFriendly: true,
    thyroidNote: 'Antiinflamatorio natural potente (gingeroles).',
  }
];
